export const FETCH_ALL_GUITARS_PENDING = 'FETCH_ALL_GUITARS_PENDING'
export const FETCH_ALL_GUITARS_SUCCESS = 'FETCH_ALL_GUITARS_SUCCESS'
export const FETCH_ALL_GUITARS_FAILED = 'FETCH_ALL_GUITARS_FAILED'

export const FETCH_ONE_GUITAR_PENDING = 'FETCH_ONE_GUITAR_PENDING'
export const FETCH_ONE_GUITAR_SUCCESS = 'FETCH_ONE_GUITAR_SUCCESS'
export const FETCH_ONE_GUITAR_FAILED = 'FETCH_ONE_GUITAR_FAILED'

export const ADD_GUITAR_PENDING = 'ADD_GUITAR_PENDING'
export const ADD_GUITAR_SUCCESS = 'ADD_GUITAR_SUCCESS'
export const ADD_GUITAR_FAILED = 'ADD_GUITAR_FAILED'

export const REMOVE_GUITAR_PENDING = 'REMOVE_GUITAR_PENDING'
export const REMOVE_GUITAR_SUCCESS = 'REMOVE_GUITAR_SUCCESS'
export const REMOVE_GUITAR_FAILED = 'REMOVE_GUITAR_FAILED'

export const UPDATE_GUITAR_PENDING = 'UPDATE_GUITAR_PENDING'
export const UPDATE_GUITAR_SUCCESS = 'UPDATE_GUITAR_SUCCESS'
export const UPDATE_GUITAR_FAILED = 'UPDATE_GUITAR_FAILED'