export const FETCH_ALL_LOCATIONS_PENDING = 'FETCH_ALL_LOCATIONS_PENDING'
export const FETCH_ALL_LOCATIONS_SUCCESS = 'FETCH_ALL_LOCATIONS_SUCCESS'
export const FETCH_ALL_LOCATIONS_FAILED = 'FETCH_ALL_LOCATIONS_FAILED'

export const FETCH_ONE_LOCATION_PENDING = 'FETCH_ONE_LOCATION_PENDING'
export const FETCH_ONE_LOCATION_SUCCESS = 'FETCH_ONE_LOCATION_SUCCESS'
export const FETCH_ONE_LOCATION_FAILED = 'FETCH_ONE_LOCATION_FAILED'

export const ADD_LOCATION_PENDING = 'ADD_LOCATION_PENDING'
export const ADD_LOCATION_SUCCESS = 'ADD_LOCATION_SUCCESS'
export const ADD_LOCATION_FAILED = 'ADD_LOCATION_FAILED'

export const REMOVE_LOCATION_PENDING = 'REMOVE_LOCATION_PENDING'
export const REMOVE_LOCATION_SUCCESS = 'REMOVE_LOCATION_SUCCESS'
export const REMOVE_LOCATION_FAILED = 'REMOVE_LOCATION_FAILED'

export const UPDATE_LOCATION_PENDING = 'UPDATE_LOCATION_PENDING'
export const UPDATE_LOCATION_SUCCESS = 'UPDATE_LOCATION_SUCCESS'
export const UPDATE_LOCATION_FAILED = 'UPDATE_LOCATION_FAILED'